HDFGroup/hsds

hsds/basenode.py
hsds/datanode.py
hsds/servicenode.py
setup.py

- The registration of datanode was improperly tested (only one node was seen) 
- A small setup.py has been added to help `pip` install
- Chunk coordinates are now computed as `I/J_K` instead of `I_J_K` (a prefix may be added to be more robust)

OpenIO integration

---

docs/kubernetes_install_azure.md

missing export value re-added to Kubernetes README.

re-add missing CONTAINERNAME export

---

docs/kubernetes_install_aws.md
k8s_deployment_aws.yml

https://github.com/HDFGroup/hsds/issues/53

Minor fixes for #53

---

CODE_OF_CONDUCT.md

Adds a code of conduct for the project

chore: create a code of conduct

---

hsds/config.py

fix(config): handle missing config keys without throwing error

---

hsds/chunk_sn.py
hsds/util/dsetUtil.py
tests/integ/value_test.py
tests/perf/nrel/nsrdb/nsrdb_test.py
tests/perf/nrel/wtk/wtk_conus.py
tools/get_s3perf.py

Updates to nsrdb_test.py for testing with various hdf5 options.

Jreadey master

---

Dockerfile
hsds/util/azureBlobClient.py
setup.py

Build docker image with azure "extras".

fix for azure install

---

docs/design/obj_store_schema/obj_store_schema_v2.md

Improve formatting of obj_store_schema_v2.md

---

tests/perf/read/read2d.py

added test for 2d reads with hyperslab, stride, and fancy index.

add perf test for 2d datasets

---

hsds/chunk_sn.py
hsds/servicenode.py

Using shared memory in docker had limited performance impact so removing to simplify code.

remove shared memory logic

---

admin/config/config.yml
docs/authorization.md
hsds/basenode.py
hsds/domain_sn.py
hsds/servicenode_lib.py
tests/integ/domain_test.py

Additional config settings to control access to non-default buckets.

update for disable access to non-default bucket - issue #138

---

README.md

added blog link for web caching

---

docs/docker_install_aws.md
docs/docker_install_azure.md
docs/docker_install_tencent.md

Add documentation for running HSDS on Tencent VM with Docker.

added docker install for tencent cloud

---

tests/integ/domain_test.py

Test fix for failure on Tencent Cloud.

fix for tencent test failure

---

hsds/basenode.py
hsds/util/k8sClient.py

Reduce excess cpu usage by only getting DN ids when there's a change in the pod ips addresses.

fix for high cpu usage on k8s - issue #199

---

hsds/basenode.py
setup.py
tests/perf/write/README.md
tests/perf/write/k8s_job.yml

Updated version to 0.7.1 - includes fix for cpu load under kubernetes.

version bump

---

docs/docker_install_aws.md
docs/docker_install_azure.md
docs/docker_install_posix.md

Clarify docker setup based on feedback from issue:  #204

add instructions on using SN_PORT env variable

---

hsds/basenode.py
hsds/util/k8sClient.py
setup.py

K8sutilfix

---

.github/workflows/python-package.yml
README.md
hsds/basenode.py
hsds/chunk_sn.py
hsds/hsds_app.py
hsds/servicenode_lib.py
hsds/util/arrayUtil.py
hsds/util/dsetUtil.py
hsds/util/fileClient.py
hsds/util/idUtil.py
hsds/util/linkUtil.py
hsds/util/s3Client.py
hsds/util/storUtil.py
runall.bat
runall.sh
setup.py
testall.py
tests/integ/domain_test.py
tests/integ/value_test.py

Fix compatibility issues with running HSDS without Docker on Windows.
Search sys bin dir for HSDS  executables (enables running using system python rather than Anaconda)

Updates for Windows compatibility and --hsds-nodocker mode (cf #209 and #210)

---

hsds/async_lib.py
hsds/util/k8sClient.py

Mistakenly was adding each IP twice for kubernetes...

Remove duplicate lines

---

hsds/async_lib.py
hsds/chunk_sn.py
hsds/domain_sn.py
hsds/dset_sn.py
hsds/group_dn.py
hsds/group_sn.py
hsds/util/dsetUtil.py
tests/integ/dataset_test.py
tests/integ/group_test.py
tests/integ/link_test.py

Add support for datasets created with compact and contiguous layouts.

Groupcreateprop

---

hsds/ctype_sn.py
hsds/domain_sn.py
hsds/dset_sn.py
hsds/group_sn.py
hsds/servicenode_lib.py
tests/integ/attr_test.py

Part of a set of changes intended to reduce the number of client requests that need to be made from the REST VOL, specifically HDFGroup/vol-rest#32

Implement path traversal in getObjectIdByPath

---

README.md
hsds/hsds_app.py

Fix search path for hsds executables on Windows.

fix for to find HSDS executables in Windows w/ Anaconda

---

hsds/util/arrayUtil.py
tests/unit/array_util_test.py

Also separates tests for getNumpyValue into encoded/not encoded, and adds array tests for each.

Fix encoded array fill values

---

hsds/dset_sn.py
hsds/util/storUtil.py
tests/integ/dataset_test.py

add support for fletcher32

---

hsds/chunklocator.py

simple fix for the chunklocator

fix arr index - tuple not list

---

admin/config/config.yml
hsds/datanode_lib.py
hsds/util/dsetUtil.py
hsds/util/storUtil.py
tests/integ/filter_test.py
tests/unit/compression_test.py
tests/unit/shuffle_test.py

Add support for linked files with bitshuffled datasets.

Bitshuffle2

---

hsds/chunk_sn.py
tests/integ/pointsel_test.py

Also adds additional tests for field selections with more than one field.

Fix selection of multiple fields in body

---

hsds/ctype_dn.py
hsds/ctype_sn.py
hsds/dset_sn.py
hsds/group_sn.py
hsds/servicenode_lib.py
tests/integ/attr_test.py
tests/integ/dataset_test.py
tests/integ/datatype_test.py
tests/integ/group_test.py

This commit adds a h5path option for post datasets and post datatypes

post with h5path for datatypes and datasets

---

hsds/dset_lib.py
hsds/dset_sn.py

Moved some more code to the dset-lib.py

refactor shape update to dset_lib

---

docs/docker_install_aws.md
docs/docker_install_posix.md

Fix reference to the old setup.py

fixed aws docker setup

---

hsds/link_sn.py
tests/integ/helper.py
tests/integ/link_test.py

raise a badrequest if titles, is used with follow_links, CreateOrder or Limit.

raise a 400 if titles is used with follow_links

---

hsds/util/httpUtil.py
hsds/util/k8sClient.py

fix spelling

---

tools/domain_check.py
tools/stor_check.py

new tools:
domain_check.py - print info about dataset, and some chunk data
stor_check.py - try reading bytes from given store bucket and key

added two tools for testing storage access

---

hsds/app.py

Fix typo in app.py documentation

---

admin/config/config.yml

fix config comments

---

README.md

remove link for serverless h5pyd

---

hsds/dset_lib.py
hsds/util/chunkUtil.py
tests/unit/chunk_util_test.py

Fix issue with off-diagonal multicoordinate selections.

fix for mutlicoordinate selection

---

docs/design/map/h5_map.md

fix typos in design doc

---

tests/integ/value_test.py
tests/unit/array_util_test.py

Added additional tests for compound and array types

added additional test for compound types

---

hsds/hsds_app.py

Replace logging.warn with logging.warning

fix logging deprecation warning

---

hsds/basenode.py
pyproject.toml

bump version to 0.9.2

---

hsds/link_sn.py
tests/integ/link_test.py

more test for get links in creation vs alphanumeric order

added additional link list tests

---

hsds/attr_sn.py
hsds/chunk_crawl.py
hsds/chunk_dn.py
hsds/chunk_sn.py
hsds/datanode_lib.py
hsds/domain_crawl.py
hsds/dset_lib.py
hsds/servicenode_lib.py
hsds/util/chunkUtil.py
hsds/util/dsetUtil.py
tests/unit/bool_parser_test.py
tests/unit/chunk_util_test.py

As per title.  Also reduce log verbosity for large compound types.

support queries is alphanum field names

---

README.md
hsds/attr_dn.py

Update links to HSDS documentation (and REST API docs)

update doc links

---

hsds/util/storUtil.py
pyproject.toml

fix for bloc buffer name change

fix for blosc interface change
