HDFGroup/hsds

- .env
- docker-compose-internal-lb.yml
- docker-compose.openio.yml
- docker-compose.posix.yml
- docker-compose.secure.yml
- docker-compose.yml
- hsds/config.py
- hsds/util/authUtil.py
- runall.sh
Re-authentication is required every `AUTH_EXPIRATION` seconds if this is set and > 0. By default, no re-authentication is required in order to preserve old behavior. Credentials set in the `passwd.txt` file never expire.
I did not see any authentication tests, so if they exist they have not been updated. Kubernetes deployment files have also not been updated since I am not as familiar with it.
> Add authentication expiration

- Dockerfile
Following https://github.com/HDFGroup/hsds/pull/35#issuecomment-606951083 :
"""
Going back to #26 - I notice that build.sh installs a lot of azure packages each time. E.g. azure-datalake-store. Is there a way to avoid these? I thought the required packages where being installed in the Docker base image. I prefer not having to deal with possible package updates with every build.
"""
This PR removes the check/installation of dependencies when installing `hsds`, so it is expected that all dependencies are already available in the base docker image.
> Do not install dependencies when building docker

- hsds/app.py
- hsds/basenode.py
- hsds/config.py
- hsds/datanode.py
- hsds/headnode.py
- hsds/servicenode.py
- setup.py
This PR builds on PR #26 which content is included here.
It is a first proposition to enable starting `hsds` as a simple application (issue #34).
There is room for improvement, but it passes the tests for both open.io and posix storage.
I takes a few options on top of those `hsds.config.get` is interpreting:
```
% hsds --help
usage: Starts hsds a REST-based service for HDF5 data.
optional arguments:
-h, --help            show this help message and exit
--bucket-dir BUCKET_DIR
Directory where to store the object store data
--bucket-name BUCKET_NAME
Name of the bucket to use (e.g., "hsds.test").
--host HOST           Address the service node is bounds with (default: localhost).
-p PORT, --port PORT  Service node port (default: 5101).
--s3-gateway S3_GATEWAY
S3 service endpoint (e.g., …
```
> Make hsds available as an application

- admin/config/config.yml
- hsds/basenode.py
Hi, thanks for working on hsds!
This allows toggling between the `list_namespaced_pod` and `list_pod_for_all_namespaces`
methods in the python kubernetes client when initializing an hsds deployment in-cluster.
Specifying a specific namespace is useful for some shared tenant deployments with
strict RBAC policies.
See this link for details:
https://kubernetes.io/docs/reference/access-authn-authz/rbac/#service-account-permissions
In deployments similar to what is described in the first example and where it is not possible to apply the RBAC configuration in `admin/kubernetes/k8s_rbac.yml`, listing namespaces will fail with the following exception:
```
======== Running on http://0.0.0.0:5101 ========
(Press CTRL+C to quit)
INFO> health check start
INFO> node_state: INITIALIZING
INFO> …
```
> add support for specifying k8s_namespace

- awslambda/chunkread/hsds/util/dsetUtil.py
- hsds/util/dsetUtil.py
Putting integers in the `select` query parameter of GET value would give an empty value.
`select=[n]` would indeed be transformed to the empty slice `[n:n]`.
In this PR, `select=[n]` is interpreted as `[n:n+1]`, yielding a slice containing the element `n`.
> Fix empty value when integers in select param

- .gitignore
- Dockerfile
- hsds/util/storUtil.py
- testall.py
The code in this branch:
1. Replaces the custom numba-based shuffle filter with the one from the numcodecs package.
1. New Dockerfile for HSDS containers that builds the numcodecs package from source (because its shuffle filter is not yet in any of the official releases). The Dockerfile uses the `continuumio/miniconda3` base image and yields an image of about 450MB.
1. Some PEP8 and gitignore housekeeping.
> Numcodecs shuffle

- hsds/basenode.py
In `k8s_update_dn_info` there is a loop that's supposed to make an `/info` request to all of the discovered DN IPs to verify that the DN has initialized successfully before adding it to the DN list. This currently incorrectly references the global copy of the list instead of the new list obtained via the k8s API and so a DN that is not yet ready can be added to the `dn_url` list and saved back into the global, causing a mismatch between `dn_urls` and `dn_ids`.
We discovered this when testing scaling the HSDS cluster while several `hsload` requests were in flight - this caused a crash in the s3syncCheck task when it made a notify root request to a DN that returned a 503 error which was not handled.
> fix reference to dn_urls in k8s_update_dn_info

- hsds/config.py
Motivated by #107. It seems that `.yaml` is the "official" extension, though numerous kubernetes examples use `.yml` leading to confusion. See https://yaml.org/faq.html.
> feat: support config files with .yaml extension

- hsds/util/authUtil.py
- hsds/util/awsLambdaClient.py
- hsds/util/query_marathon.py
- hsds/util/s3Client.py
- tests/unit/storUtilTest.py
- tools/bucket_scan.py
- tools/create_toplevel_domain_json.py
- tools/delete_bucket.py
- tools/get_s3json.py
- tools/link_mod.py
- tools/list_objects.py
- tools/root_delete.py
- tools/root_scan.py
In `aiobotocore` 2.0.0 remove `get_session` at top level, as point out in #110 
The fixs are import from `aiobotocore.sessio`
> fix get_session import after aiobotocore 2.0.0

- lambda_function.py
Fixes an issue with lambda that was introduced about a month ago with changes supporting Windows (I think). Those changes removed the auto-generated socket directory. This reintroduces it in the lambda function only. I'm not at all confident that this is where you'd want this, and will be glad to modify if you have some feedback about a proper place to put it per your coding standards.
> Lambda socket dir

- .github/workflows/docker-image.yml
This workflow will automatically build the docker image and push it to dockerhub with specific tags as configured in the "Docker meta" step. 
Currently, it is set to use the following tags: 
Push to master -  'master', "GIT_SHA"
Release  (X.Y.Z)- 'X', "X.Y", "X.Y.Z"
This can be configured as described here https://github.com/docker/metadata-action
The repository maintainers would need to create two secrets for the repository,   DOCKERHUB_USERNAME and DOCKERHUB_TOKEN to enable pushing the image
> Automatically tag and push docker images

- hsds/util/s3Client.py
Thanks for all the work on HSDS!
Previously, curl's progress bar was printed to the logs which made
the logs hard to read. Instead, use curl's '--no-progress-meter' flag to
supress the output without hiding warnings or errors.
For example, I had lines like the one below.
```
dn1 ERROR> Error getting IAM role credentials: b'  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:-- …
```
> Don't output curl progress bar to logs when fetching S3 token

- hsds/app.py
I ran into this today where I mistyped the `--config_dir` option as `--config-dir` and then spent a long time looking through my config files to work out why requests to the server weren't working. I feel it's nicer for users to be told if a commandline argument is wrong as it can be easy to make this sort of mistake. The `extra_args` variable didn't seem to be used anyway.
Thanks again for all the work on HSDS, it looks like there has been lots of development recently.
> Disallow unknown commandline arguments

- hsds/chunk_sn.py
small fix to avoid undefined variable error
> initialize variable to avoid undefined error during exception

- Dockerfile
Add curl to Dockerfile (needed for running on EC2 with implicit credentials)
> add curl to Dockerfile

- hsds/chunk_sn.py
According to the aiohttp source, the correct order should be (max, actual)
Fixes #221
> Flip arg order in HTTPRequestEntityTooLarge call

- hsds/ctype_sn.py
Responses for other object types (groups, datasets) don't include the bucket, so this makes it more consistent.
> Fix GET datatype including bucket in domain

- hsds/basenode.py
- hsds/ctype_sn.py
- hsds/domain_sn.py
- hsds/dset_sn.py
- hsds/group_sn.py
- hsds/link_sn.py
- hsds/servicenode_lib.py
- hsds/util/httpUtil.py
- tests/integ/helper.py
- tests/integ/link_test.py
Implemented the 'recurse_until_hard' option for clients which, when used with h5path, tells the server to keep following symbolic links until it finds a hard link (e.g. an actual object). This allows a client to get any object by path in a single request.
This adds support for external link traversal in getObjectIdByPath.
This is backwards-compatible with old clients.
On the icesat2-benchmark, this decreased the time taken from ~4 seconds (with the link traversal changei n #219) to ~3.6 seconds.
> Implement recurse until hard link by h5path

- hsds/domain_sn.py
- hsds/servicenode_lib.py
This is useful for H5Ovisit in the REST VOL.
Also fix `getObjectIdByPath` not passing the values of `follow_soft_links` and `follow_external_links` to recursive calls of itself.
> Return href information for h5path requests

- hsds/util/arrayUtil.py
- tests/unit/array_util_test.py
This lets clients read from an empty attribute without causing an internal server error.
Previously, a value in `data_json` being `None` caused errors when passed to `np.array`.
> Fix jsonToArray error on empty data read

- admin/docker/docker-compose-internal-lb.yml
- admin/docker/docker-compose.aws.yml
- admin/docker/docker-compose.azure.yml
- admin/docker/docker-compose.posix.yml
- admin/docker/docker-compose.yml
- runall.sh
added  optional argument to runall.sh (see runall.sh --help)  to create mutliple sn containers.
> add runall.sh option for sn_cores

- hsds/async_lib.py
- hsds/chunk_sn.py
- hsds/dset_dn.py
- hsds/dset_sn.py
- hsds/util/dsetUtil.py
- tests/integ/dataset_test.py
Enable PUT shape to reduce extent
Also - fix errors showing up in async process.
> Allow PUT shape to reduce extent

- hsds/attr_sn.py
- hsds/chunk_sn.py
- hsds/dset_sn.py
- hsds/util/arrayUtil.py
- hsds/util/hdf5dtype.py
- tests/integ/attr_test.py
- tests/integ/dataset_test.py
- tests/integ/value_test.py
- tests/unit/array_util_test.py
- tests/unit/hdf5_dtype_test.py
Update for UTF8 fixed width strings
> add support for fixed width UTF8 strings - #270

- hsds/attr_sn.py
- hsds/chunk_sn.py
- hsds/chunklocator.py
- hsds/util/arrayUtil.py
- hsds/util/chunkUtil.py
- tests/unit/array_util_test.py
This is the same issue that was partially fixed in #237, where `None` elements in a `value` array caused issues in the helper `jsonToArray`. This covers the case where the entire `value` array is `None` (e.g. an attribute that was created but not written to). It now returns an empty numpy array instead of throwing an exception. 
This also makes HSDS log the error messages `jsonToArray` produces, and adds a try/except block when doing a bytes decode that can fail.
> Fix jsonToArray on None array

- hsds/dset_sn.py
- hsds/util/dsetUtil.py
- hsds/util/storUtil.py
- pyproject.toml
- testall.py
- tests/integ/filter_test.py
- tests/unit/compression_test.py
- tests/unit/hdf5_dtype_test.py
- tests/unit/shuffle_test.py
Add support for the bitshuffle filter
> add support for bitshuffle

- hsds/util/dsetUtil.py
- hsds/util/storUtil.py
- tests/integ/dataset_test.py
Allows n-bit and scale offset filters to be specified in the DCPL, without actually implementing the filters themselves.
Also fixes the typo for the filter name `scaleoffet -> scaleoffset`
Resolves #285
> Allow n-bit and scale offset filters in DCPL

- hsds/chunk_crawl.py
- hsds/datanode_lib.py
- hsds/dset_lib.py
- hsds/util/hdf5dtype.py
- tests/integ/value_test.py
Reading and writing to array/nested array type objects is still buggy, but this is a step in the right direction.
Previously, the check on the return value of getFillValue would throw an error when the datatype was H5T_ARRAY.
> Support creation of array/nested array types

- hsds/util/fileClient.py
This is redundant since `_getFilePath` already normalizes the path, but this quiets the CodeQL warnings.
> Silence user-defined path warning

- hsds/chunk_sn.py
- tests/integ/pointsel_test.py
- tests/integ/vlen_test.py
Response for point selection of vlen type datasets wasn’t being decided properly
> fix for point selection of vlen type

- hsds/attr_sn.py
- hsds/domain_crawl.py
- hsds/link_sn.py
- tests/integ/attr_test.py
- tests/integ/link_test.py
Fix for Limit param to work with follow links
> enable limit for followlinks

- hsds/dset_sn.py
- hsds/group_sn.py
- hsds/servicenode_lib.py
- tests/integ/group_test.py
Add h5path option to post groups
> group post with h5path option

- tests/perf/arrayperf/bytes_to_vlen.c
A C implementation of the performance test added in #301. It's ~1000x faster than the python version of the same functions (0.000248 seconds for `array_to_bytes`, 0.000353 seconds for `bytes_to_array`), indicating that using Cython for this process could be exponentially faster than the current implementation.
> Add C benchmark for vlen buffer management

- hsds/link_sn.py
- tests/integ/link_test.py
Currently, `PUT_Links` expects `grp_ids` and `POST_Links` expects `group_ids`.
> Make link API consistently expect 'grp_ids'

- hsds/link_sn.py
- tests/integ/link_test.py
When providing a list of link titles and a list of group ids, `POST_Links` is ignoring the provided titles and returning all links in the provided groups. It should return links with the specified titles from each target group, similar to `PUT_Links`.
> Fix POST_Links incorrectly returning all links

- tests/integ/link_test.py
The test used the old parameter `group_ids` instead of the new `grp_ids`, causing the parameter to go unrecognized and the test to fail every time.
> Fix link test using old param name

- tests/perf/arrayperf/bytes_to_vlen.py
Performance test for vlen chunk serialization
> added bytes_to_vlen perf test

- hsds/attr_dn.py
- hsds/chunk_dn.py
- hsds/ctype_dn.py
- hsds/domain_sn.py
- hsds/dset_dn.py
- hsds/group_dn.py
- hsds/link_dn.py
- hsds/util/domainUtil.py
- tests/unit/domain_util_test.py
This fixes a security issue where bucket strings could end up on the command line when using the Azure backend. 
Not all of the [AWS bucket naming rules](https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html) are enforced - only the ones that are relevant to preventing security exploits, and can be checked directly by HSDS.
Also fixed PUT_Attributes and POST_Datatype in the DN not retrieving bucket from the body.
> Restrict bucket names to alphanumeric characters and underscores

- hsds/chunk_crawl.py
- hsds/chunk_sn.py
- tests/integ/pointsel_test.py
When base64-encoded variable-length data to a point selection, HSDS converts the received base64 directly to a numpy array of the appropriate vlen type in `PUT_Value -> _getRequestData`.  `write_point_sel`, expects the provided data to be JSON and attempts to parse it to an array again, causing an error.
This changes `write_point_sel` to check if its received data is already decoded.
> Fix writing base64 encoded vlen data to point selection

- build.sh
- hsds/chunk_dn.py
- hsds/dset_lib.py
- hsds/util/boolparser.py
- hsds/util/chunkUtil.py
- tests/integ/query_test.py
- tests/unit/chunk_util_test.py
Enable dataset queries with opional "where in" syntax.
E.g.:
"(open > 5.0) & (close < 5.0) where symbol in (b'MCD', b'KO', b'JNJ')"
> Add support for "where in" queries

- hsds/chunk_sn.py
- hsds/util/hdf5dtype.py
- tests/integ/vlen_test.py
- tests/unit/hdf5_dtype_test.py
The content_length header wasn't being set to the correct number of bytes when field selections are used.
> set correct content_length when requesting data with field selection

- hsds/util/domainUtil.py
- tests/unit/domain_util_test.py
Some NREL buckets have hyphens, so we should definitely allow those. Allowing periods make HSDS at least as permissive as AWS's bucket name rules.
> Allow periods and hyphens in bucket names

- hsds/util/fileClient.py
The loop of getting file stats can take a lot of time on POSIX setup, should fix #332 
cc @jreadey
> add additional asyncio.sleep in list_keys loop over files, fixes #332

- hsds/basenode.py
- hsds/chunk_dn.py
- hsds/datanode_lib.py
- hsds/util/domainUtil.py
- hsds/util/idUtil.py
- hsds/util/s3Client.py
- hsds/util/storUtil.py
- runall.sh
- tests/integ/pointsel_test.py
- tests/integ/query_test.py
- tests/integ/vlen_test.py
- tests/unit/domain_util_test.py
- tests/unit/id_util_test.py
- tests/unit/stor_util_test.py
This PR enables HSDS to support different storage back ends (posix, s3, azure blob) in the same running instance.
If the bucket query parameter is pre-appended with a storage specifier, the corresponding driver will be used for reads and writes.
Currently supported prefixes are:
- "s3://" - aws s3
- "file://" - posix 
- "https://account_name>.blob.windows.net/" - azure  blob storage
If no prefix is used, the default driver will be used.  Where default is the first one meeting the given precondition from this list:
- "file://" - if root_dir config is set
- "s3://" - if aws_s3_gateway is set
- "https....net/" - if azure_connection_string is set
- "file://" - if none of the above apply
> update for multi-storage drivers

- .github/workflows/python-package.yml
- docs/design/azure/azure.md
- docs/docker_install_aws.md
- docs/docker_install_azure.md
- docs/docker_install_posix.md
- docs/docker_install_tencent.md
- docs/setup_docker.md
- runall.sh
- stopall.sh
- tests/perf/write/start.sh
- tests/perf/write/stop.sh
Docker Compose v1 is deprecated - see #339.
This replaces CLI invocations of `docker-compose` with `docker compose`, which uses v2 instead.
To test the new scripts, this adds a CI workflow to build and test with Docker. Docker + Windows still has some issues, so tests with that combination are skipped for now. I also moved h5pyd tests from being a matrix option to the default, since that doubled the number of workflows for no good reason.
Results of workflow run can be seen [here](https://github.com/mattjala/hsds/actions/runs/8606446380).
Resolves #339.
> Update scripts to use docker compose v2

- hsds/async_lib.py
- hsds/basenode.py
- hsds/ctype_dn.py
- hsds/datanode.py
- hsds/datanode_lib.py
- hsds/domain_dn.py
- hsds/domain_sn.py
- hsds/dset_dn.py
- hsds/group_dn.py
- hsds/link_dn.py
- hsds/util/timeUtil.py
- tests/integ/link_test.py
On Windows, `time.time()` has a low resolution (~16ms), so objects created in sequence sometimes have the same 'created' timestamp.
Creation time is now computed by adding the precise time elapsed since node startup (from `time.perf_counter`) to the recorded unix time at node startup, in the new helper `timeUtil.getNow()`.
Fixes #344
> Fix inaccurate creation order on Windows

- hsds/chunk_sn.py
- tests/integ/vlen_test.py
- Remove `testPutVLenUTF8`, since the case it was testing (sequence of variable-length strings) isn't supported by HSDS.
- `_doHyperslabWrite` now causes the client to receive an internal server error if it fails, instead of silently failing and still returning 200.
> Return internal server error on failed hyperslab write

- admin/docker/docker-compose-internal-lb.yml
- admin/docker/docker-compose.aws.yml
- admin/docker/docker-compose.azure.yml
- admin/docker/docker-compose.posix.yml
- admin/docker/docker-compose.yml
Remove version key work in docker compose to avoid deprecation warning.  See: https://github.com/compose-spec/compose-spec/blob/master/spec.md#version-top-level-element.
> remover docker compose version

- hsds/domain_sn.py
- hsds/util/domainUtil.py
- tests/integ/domain_test.py
- tests/integ/helper.py
- tests/unit/domain_util_test.py
Removing support for dns-style domain names.
Previously a domain path like: "/home/test_user1/tall.h5" could be expressed as:
"tall.test_user1.home".
The DNS style derived from the original rest HDF white paper: https://www.hdfgroup.org/pubs/papers/RESTful_HDF5.pdf,
but this doesn't seem to have been used in practice or have any special utility over the more common style.  Also, there's some ambiguity with dots that are used as part of the filename rather than a folder separator.
> remove dns style for domains

- hsds/async_lib.py
- tests/integ/value_test.py
After #349, Windows still sometimes has a scan timeout due to `getNow` inaccuracy between nodes. This reverts the scan timestamps to use `time.time()`. Because the [scan check](https://github.com/HDFGroup/hsds/blob/master/hsds/domain_sn.py#L916) now accepts an equal timestamp as satisfying the scan request, the inaccuracy of `time.time()` shouldn't be a problem in this case.
> Fix scan timeout on Windows

- tests/integ/domain_test.py
`testCreateDomainNodeIds` sometimes gets an HTTPConflict trying to create its domain. This is because the domain helpers generate a domain name based on the current timestamp and the given domain name. Both this test and `testCreateDomain` use the same given domain name of `newdomain.h6`, and because of Windows' low time resolution, sometimes both domains are created at the same timestamp and have a name conflict. 
This PR changes the name of the domain in `testCreateDomainNodeIds` to avoid the conflict regardless of timestamp.
Resolves #353
> Fix 409 Conflict in domain test on Windows

- docs/design/obj_store_schema/obj_store_schema_v2.md
Links seem to be stored as sub-objects in the same manner as attributes, so it makes sense to describe them here. 
Also fixes some typos.
> Add link description to schema doc

- hsds/util/s3Client.py
S3 was raising PermanentRedirect error when a bucket did not exist.  Catching this and returning 404 for put or get object.
> Return 404 for S3 PermanentRedirect exceptions

- hsds/util/globparser.py
- tests/unit/glob_parser_test.py
Pattern with asterisks at the end are incorrectly considered matches, even if the preceding pattern does not match
> Fix some incorrect pattern parsing

- .github/workflows/dependency-review.yml
- pyproject.toml
- requirements.txt
The requests 2.32.0 update from a couple days ago breaks requests-unixsocket for connections to a local socket. There is [a PR](https://github.com/msabramo/requests-unixsocket/pull/72) to requests-unixsocket, but until that gets in we should constrain the requests version
> Use old requests version

- hsds/domain_sn.py
- hsds/servicenode_lib.py
- hsds/util/domainUtil.py
- hsds/util/s3Client.py
- tests/integ/config.py
- tests/integ/domain_test.py
- tests/integ/group_test.py
- tests/integ/setup_test.py
> clean up getdomain logic

- hsds/util/s3Client.py
- pyproject.toml
- requirements.txt
Use v2 interface for list keys (compatible with S3 express buckets)
> Listkeysv2

- README.md
- build.sh
- tests/integ/config.py
Updates so quickstart instructions work
> fixes for quick start usage

- pyproject.toml
- requirements.txt
Numpy just had its [first major release in years](https://github.com/numpy/numpy/releases/tag/v2.0.0), with breaking changes to its API. We should eventually  add compatibility, but for now just restrict the numpy dependency to a pre-2.0.0 version.
> Prevent use of new major numpy version

- hsds/app.py
Fix for #379 - with this change HS_USERNAME/HS_PASSWORD will be ignored if password_file is passed to hsds app.
> update for hsds app arg processing

- hsds/util/storUtil.py
scaleoffset filter not supported by blosc, so ignore the compressor.
> ignore scaleoffset compression

- hsds/chunk_sn.py
- hsds/dset_lib.py
- hsds/dset_sn.py
- hsds/util/chunkUtil.py
- hsds/util/dsetUtil.py
- testall.py
- tests/integ/pointsel_test.py
- tests/integ/value_test.py
- tests/unit/chunk_util_test.py
- tests/unit/dset_util_test.py
Enable selections such as [::, [1,4,5],[2,8,6]
> Enable fancy selection with multiple coordinates

- admin/docker/docker-compose-internal-lb.yml
- admin/docker/docker-compose.aws.yml
- admin/docker/docker-compose.azure.yml
- admin/docker/docker-compose.posix.yml
- admin/docker/docker-compose.yml
With this change, runall.sh works on e.g. macos with Apple Silicon.
> Set platform in docker-compose so it works on other platforms than amd64

- hsds/datanode_lib.py
- hsds/util/storUtil.py
- tests/unit/compression_test.py
Fix for issue: https://github.com/HDFGroup/hsds/issues/393
> fix for contiguousref datasets

- Pipfile.lock
Working around CI check issues with #376
> Bump urllib3 from 1.26.18 to 1.26.19

- docs/design/map/h5_map.md
> map design doc

- hsds/dset_dn.py
- tests/integ/dataset_test.py
Don't change zero extents to one on a PUT datashape requests.
> extend fix

- tests/integ/helper.py
- tests/perf/stream/helper.py
- Prevent domain name conflict during tests
Tests use the timestamp to generate unique domain names and avoid conflicts. On windows, the timestamp resolution is low enough that these sometimes have the same timestamp and still conflict with a 409 error.
This replaces the timestamp with an 8-character random string, which should have less than a one in a million chance of a name conflict.
We should probably remove the duplicated test helpers at some point, but it seems like setting up a shared import between the tests that would use it is non-trivial
> Fix CI failures due to domain name conflits

- .github/workflows/python-package.yml
ubuntu-latest now refers to Ubuntu 24.04 instead of 22.04.
> Add Ubuntu 22.04 back into CI

- docs/keycloak_setup.md
- hsds/util/jwtUtil.py
- tests/unit/chunk_util_test.py
Updates to support more recent KeyCloak versions
> fix for keycloak authentication

- tests/integ/group_test.py
- tests/integ/link_test.py
`link_creation_order` isn't a supported parameter. The name of the intended option is `CreateOrder`.
> Fix CreateOrder option in group/link tests

- tests/integ/dataset_test.py
- tests/integ/filter_test.py
- tests/integ/helper.py
- tests/integ/pointsel_test.py
- tests/integ/query_test.py
- tests/integ/value_test.py
- tests/integ/vlen_test.py
- tests/perf/stream/helper.py
Resources conflicts due to resources sharing names in the same domain sometimes cause failures in CI ([example](https://github.com/mattjala/hsds/actions/runs/12468559688/job/34799969915)).
This randomizes names of test dsets/links to prevent conflicts.
> Prevent resource conflicts in tests

- hsds/util/hdf5dtype.py
- hsds/util/idUtil.py
> fix comment grammer

- hsds/attr_sn.py
- hsds/chunk_sn.py
Numpy 2.3.0 deprecated the default (binary) mode of `np.fromstring()`. This replaces use of `np.fromstring()` with `np.frombuffer()`, which should have no change in behavior.
> Replace deprecated numpy fromstring()

- .devcontainer/Dockerfile
- .github/workflows/python-package.yml
- hsds/basenode.py
- pyproject.toml
Removing python 3.9 support and bump version
> bump version, remove python 3.9 support
